### ISSUE TITLE
How to star the whole platform

### ISSUE THREAD

**Issue by xtermsoft** [Viveckh/Veniqa#94]
I am trying to start the shopping server and I keep getting the following error 

```
NODE_ENV=development VENIQA_ENV=development npm run devstart

> veniqa-server@0.0.0 devstart /Users/username/Desktop/Veniqa/shopping-server
> nodemon --exec babel-node ./bin/www

[nodemon] 1.18.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node ./bin/www`
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '.env.development'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/Users/username/Desktop/Veniqa/shopping-server/config.js:25:43)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at loader (/Users/username/Desktop/Veniqa/shopping-server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/username/Desktop/Veniqa/shopping-server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)

```
I am quite new to vue and node. Could you please help me out with how to boot up your entire platform? 

Thanks.

**Comment by xtermsoft** [comment]
So what I did is copied the .env.development file from the web-client folder and pasted it in the server directory and it worked.

**Comment by xtermsoft** [comment]
I am now getting a DB error 

```
username@username shopping-server % npm run devstart

> veniqa-server@0.0.0 devstart /Users/username/Desktop/Veniqa/shopping-server
> nodemon --exec babel-node ./bin/www

[nodemon] 1.18.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node ./bin/www`
/Users/username/Desktop/Veniqa/shopping-server/node_modules/winston-mongodb/lib/winston-mongodb.js:55
    throw new Error('You should provide db to log to.');
    ^

Error: You should provide db to log to.
    at new exports.MongoDB (/Users/username/Desktop/Veniqa/shopping-server/node_modules/winston-mongodb/lib/winston-mongodb.js:55:11)
    at Object.<anonymous> (/Users/username/Desktop/Veniqa/shopping-server/logging/logger.js:32:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at loader (/Users/username/Desktop/Veniqa/shopping-server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/username/Desktop/Veniqa/shopping-server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/username/Desktop/Veniqa/shopping-server/database/dbConnection.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at loader (/Users/username/Desktop/Veniqa/shopping-server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/username/Desktop/Veniqa/shopping-server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[nodemon] app crashed - waiting for file changes before starting...

```

Which file do I enter the mongoDB credentials and the API keys. I am sorry but I am really confused. 

Thanks.
